# Consumes workflow from shared .github repo

name: Code Quality

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-quality:
    uses: opencloudhub/.github/.github/workflows/ci-code-quality.yaml@main
